# Generated by Django 5.2.17 on 2026-08-05 21:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code Infraction')),
                ('libelle', models.CharField(max_length=200, verbose_name="Libellé de l'infraction")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Montant de l'amende (FCFA)")),
                ('degre_gravite', models.CharField(choices=[('MINEURE', 'Mineure'), ('MOYENNE', 'Moyenne'), ('GRAVE', 'Grave'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut_actif', models.BooleanField(default=True, verbose_name='Infraction Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('AGENT', 'Agent Verbalisateur'), ('CITOYEN', 'Citoyen')], default='CITOYEN', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro de téléphone')),
                ('nin_carte_identite', models.CharField(blank=True, max_length=50, null=True, verbose_name="NIN / Carte d'identité")),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse de résidence')),
                ('badge_agent', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de matricule / Badge')),
                ('service_agent', models.CharField(blank=True, max_length=100, null=True, verbose_name='Service (ex. CCR, Gendarmerie)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contravention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro Contravention')),
                ('immatriculation_vehicule', models.CharField(max_length=50, verbose_name='Immatriculation du véhicule')),
                ('type_vehicule', models.CharField(choices=[('MOTO', 'Moto / Deux-roues'), ('VOITURE', 'Voiture de tourisme'), ('CAMION', 'Camion / Poids lourd'), ('MINIBUS_SOTRAMA', 'Minibus (Sotrama / Dourouni)'), ('AUTRE', 'Autre véhicule')], default='VOITURE', max_length=30)),
                ('date_contravention', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date & Heure de la constatation')),
                ('lieu_adresse', models.CharField(max_length=255, verbose_name="Lieu de l'infraction / Adresse")),
                ('commune', models.CharField(choices=[('Commune I', 'Bamako - Commune I'), ('Commune II', 'Bamako - Commune II'), ('Commune III', 'Bamako - Commune III'), ('Commune IV', 'Bamako - Commune IV'), ('Commune V', 'Bamako - Commune V'), ('Commune VI', 'Bamako - Commune VI'), ('Kati', 'Kati'), ('Autre', 'Autre localité')], default='Commune III', max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant à payer (FCFA)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée (Impayée)'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée / Rejetée')], default='EN_ATTENTE', max_length=30)),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Observations / Remarques de l'agent")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contraventions_creees', to=settings.AUTH_USER_MODEL)),
                ('citoyen', models.ForeignKey(limit_choices_to={'role': 'CITOYEN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contraventions_citoyen', to=settings.AUTH_USER_MODEL)),
                ('infraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contraventions', to='core.infraction')),
            ],
            options={
                'ordering': ['-date_contravention'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence Transaction')),
                ('mode_paiement', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('MOOV_MONEY', 'Moov Money (Moov Africa)'), ('CARTE_BANCAIRE', 'Carte Bancaire (UBA / BDM / BDMS)'), ('ESPECES', 'Espèces au guichet')], default='ORANGE_MONEY', max_length=30)),
                ('statut', models.CharField(default='SUCCES', max_length=20)),
                ('contravention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='core.contravention')),
            ],
        ),
    ]
