# Generated by Django 5.2.17 on 2026-08-05 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_infraction_code_registrenationalnina'),
    ]

    operations = [
        migrations.AddField(
            model_name='contravention',
            name='fiche_nina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contraventions', to='core.registrenationalnina'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='nom_contrevenant_saisi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom complet contrevenant NINA'),
        ),
        migrations.AlterField(
            model_name='contravention',
            name='citoyen',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CITOYEN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contraventions_citoyen', to=settings.AUTH_USER_MODEL),
        ),
    ]
