# Generated by Django 4.2.30 on 2026-08-06 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contravention_fiche_nina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Litige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(verbose_name='Motif de contestation')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='litiges/', verbose_name='Pièce justificative')),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('decision', models.TextField(blank=True, null=True, verbose_name="Décision de l'administration")),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('contravention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='litige', to='core.contravention')),
            ],
            options={
                'ordering': ['-date_depot'],
            },
        ),
        migrations.CreateModel(
            name='GPSLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse géocodée')),
                ('contravention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gps_location', to='core.contravention')),
            ],
        ),
    ]
