# Generated by Django 5.2.17 on 2026-08-05 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraction',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code Infraction'),
        ),
        migrations.CreateModel(
            name='RegistreNationalNINA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin_nina', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Numéro NINA / NIN')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('telephone', models.CharField(db_index=True, max_length=30, verbose_name='Numéro de téléphone')),
                ('numero_permis', models.CharField(blank=True, max_length=50, verbose_name='N° Permis de conduire')),
                ('statut_permis', models.CharField(choices=[('VALIDE', 'Permis Valide'), ('SUSPENDU', 'Permis Suspendu'), ('EXPIRE', 'Permis Expiré')], default='VALIDE', max_length=20)),
                ('adresse_quartier', models.CharField(max_length=150, verbose_name='Adresse / Quartier')),
                ('commune', models.CharField(max_length=50, verbose_name='Commune de résidence')),
                ('immatriculation_vehicule', models.CharField(blank=True, max_length=50, verbose_name='Véhicule principal immatriculé')),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiche_nina', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
