# Generated by Django 4.2.30 on 2026-08-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_litige_gpslocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contravention',
            name='photo_preuve',
            field=models.ImageField(blank=True, null=True, upload_to='preuves/', verbose_name='Preuve photographique'),
        ),
    ]
